spring.jackson.serialization.INDENT_OUTPUT: true

logging.level:
  org.springframework: ERROR
  org.elasticsearch: ERROR
  org.hibernate: ERROR
  io.undertow: ERROR
  org.xnio: ERROR
  org.apache: ERROR
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080
  address: 127.0.0.1

management.port: -1

spring:
  datasource:
    username: sammy
    password: password
    platform: mysql
    url: "jdbc:mysql://localhost:3306/order_database"
